// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package privatevcs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Gateway_ConnectClient, error)
}

type gatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayClient(cc grpc.ClientConnInterface) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Gateway_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &Gateway_ServiceDesc.Streams[0], "/privatevcs.Gateway/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &gatewayConnectClient{stream}
	return x, nil
}

type Gateway_ConnectClient interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ClientStream
}

type gatewayConnectClient struct {
	grpc.ClientStream
}

func (x *gatewayConnectClient) Send(m *Response) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gatewayConnectClient) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GatewayServer is the server API for Gateway service.
// All implementations must embed UnimplementedGatewayServer
// for forward compatibility
type GatewayServer interface {
	Connect(Gateway_ConnectServer) error
	mustEmbedUnimplementedGatewayServer()
}

// UnimplementedGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayServer struct {
}

func (UnimplementedGatewayServer) Connect(Gateway_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedGatewayServer) mustEmbedUnimplementedGatewayServer() {}

// UnsafeGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServer will
// result in compilation errors.
type UnsafeGatewayServer interface {
	mustEmbedUnimplementedGatewayServer()
}

func RegisterGatewayServer(s grpc.ServiceRegistrar, srv GatewayServer) {
	s.RegisterService(&Gateway_ServiceDesc, srv)
}

func _Gateway_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayServer).Connect(&gatewayConnectServer{stream})
}

type Gateway_ConnectServer interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ServerStream
}

type gatewayConnectServer struct {
	grpc.ServerStream
}

func (x *gatewayConnectServer) Send(m *Request) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gatewayConnectServer) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Gateway_ServiceDesc is the grpc.ServiceDesc for Gateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "privatevcs.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Gateway_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "privatevcs.proto",
}
