name: Build & Publish

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish:
    name: 🚀 Build and publish VCS Agent
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
        with: { fetch-depth: 0 }

      - name: Publish binary & Docker image
        uses: ./.github/workflows/publish
        with:
          aws_role_to_assume: ${{ startsWith(github.ref, 'refs/tags/v') && secrets.AWS_ROLE_TO_ASSUME || secrets.PREPROD_AWS_ROLE_TO_ASSUME }}
          ecr_repository_url: ${{ startsWith(github.ref, 'refs/tags/v') && secrets.PUBLIC_VCS_AGENT_ECR_REPOSITORY_URL || secrets.PREPROD_PUBLIC_VCS_AGENT_ECR_REPOSITORY_URL }}
          aws_bucket: ${{ startsWith(github.ref, 'refs/tags/v') && secrets.AWS_S3_BUCKET || secrets.PREPROD_AWS_S3_BUCKET }}
          cloudfront_distribution: ${{ startsWith(github.ref, 'refs/tags/v') && secrets.DISTRIBUTION || secrets.PREPROD_DISTRIBUTION }}
          bugsnag_api_key: ${{ startsWith(github.ref, 'refs/tags/v') && secrets.BUGSNAG_API_KEY || secrets.PREPROD_BUGSNAG_API_KEY }}
          gpg_key_id: ${{ secrets.GPG_KEY_ID }}
          gpg_base64_key: ${{ secrets.GPG_KEY_BASE64 }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          r2_bucket: ${{ startsWith(github.ref, 'refs/tags/v') && vars.R2_BUCKET || vars.PREPROD_R2_BUCKET }}
          r2_endpoint: ${{ startsWith(github.ref, 'refs/tags/v') && vars.R2_ENDPOINT_URL || vars.PREPROD_R2_ENDPOINT_URL }}
          r2_access_key_id: ${{ startsWith(github.ref, 'refs/tags/v') && secrets.R2_ACCESS_KEY_ID || secrets.PREPROD_R2_ACCESS_KEY_ID }}
          r2_secret_access_key: ${{ startsWith(github.ref, 'refs/tags/v') && secrets.R2_SECRET_ACCESS_KEY || secrets.PREPROD_R2_SECRET_ACCESS_KEY }}
          cloudflare_zone_id: ${{ startsWith(github.ref, 'refs/tags/v') && vars.EU_DOWNLOADS_CLOUDFLARE_ZONE_ID || vars.PREPROD_DOWNLOADS_CLOUDFLARE_ZONE_ID }}
          cloudflare_purge_token: ${{ startsWith(github.ref, 'refs/tags/v') && secrets.EU_CLOUDFLARE_CACHE_PURGE_TOKEN || secrets.PREPROD_CLOUDFLARE_CACHE_PURGE_TOKEN }}
          cloudflare_purge_prefix: ${{ startsWith(github.ref, 'refs/tags/v') && vars.EU_DOWNLOADS_CLOUDFLARE_PURGE_PREFIX || vars.PREPROD_DOWNLOADS_CLOUDFLARE_PURGE_PREFIX }}
